INSERT INTO PRODUCTS (VA_PRODUCT_NAME, BO_PRODUCT_SUITABLE, VA_PRODUCT_BRAND, DA_PRODUCT_ENTRY_DATE,
                      DA_PRODUCT_EXPIRATION_DATE)
VALUES ('Leche descremada', true, 'La Serenísima', CURRENT_DATE, '2025-05-12');

INSERT INTO PRODUCTS (VA_PRODUCT_NAME, BO_PRODUCT_SUITABLE, VA_PRODUCT_BRAND, DA_PRODUCT_ENTRY_DATE,
                      DA_PRODUCT_EXPIRATION_DATE)
VALUES ('Harina leudante', false, 'Morixe', CURRENT_DATE, '2026-03-10');

INSERT INTO PRODUCTS (VA_PRODUCT_NAME, BO_PRODUCT_SUITABLE, VA_PRODUCT_BRAND, DA_PRODUCT_ENTRY_DATE,
                      DA_PRODUCT_EXPIRATION_DATE)
VALUES ('Arroz', true, 'Dos Hermanos', CURRENT_DATE, '2026-01-10');

INSERT INTO PRODUCTS (VA_PRODUCT_NAME, BO_PRODUCT_SUITABLE, VA_PRODUCT_BRAND, DA_PRODUCT_ENTRY_DATE,
                      DA_PRODUCT_EXPIRATION_DATE)
VALUES ('Puré de tomate', true, 'La Campagnola', CURRENT_DATE, '2026-01-30');

INSERT INTO PRODUCTS (VA_PRODUCT_NAME, BO_PRODUCT_SUITABLE, VA_PRODUCT_BRAND, DA_PRODUCT_ENTRY_DATE,
                      DA_PRODUCT_EXPIRATION_DATE)
VALUES ('Avena integral extrafina', false, 'Quaker', CURRENT_DATE, '2025-11-26')